{% set name = "pcdswidgets" %}
{% set version = "2.0.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/p/pcdswidgets/pcdswidgets-{{ version }}.tar.gz
  sha256: 47166d20c90a520cb132aa88203cb8b5c96bccc4b27622caca8af5ac99e2dc93

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - pydm >=1.9.0
    - qtpy
    - pyqt >=5

test:
  requires:
    - python {{ python_min }}
  imports:
    - pcdswidgets

about:
  home: https://github.com/pcdshub/pcdswidgets
  doc_url: https://pcdshub.github.io/pcdswidgets/
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: PyDM library of widgets for the Linac Coherent Light Source (LCLS) at SLAC

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
