{% set name = "pcdswidgets" %}
{% set version = "1.0.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/pcdswidgets/archive/v{{ version }}.tar.gz
  sha256: 9eb64e1f4d5d53134e85778c5ac5fb92ad54be6a93e195f5a931591a398b4f96

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - pydm >=1.9.0
    - qtpy
    - pyqt >=5

test:
  requires:
    - python {{ python_min }}
  imports:
    - pcdswidgets

about:
  home: https://github.com/pcdshub/pcdswidgets
  doc_url: https://pcdshub.github.io/pcdswidgets/
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: PyDM library of widgets for the Linac Coherent Light Source (LCLS) at SLAC

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
