{% set name = "pcdswidgets" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/pcdswidgets/archive/v{{ version }}.tar.gz
  sha256: 520e9c3b6f50bbe6150a41fba778a0cf0c83d3be5ea4e14c9e698d6791fd7353

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pydm >=1.9.0
    - qtpy

test:
  imports:
    - pcdswidgets

about:
  home: https://github.com/pcdshub/pcdswidgets
  doc_url: https://pcdshub.github.io/pcdswidgets/
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: PyDM library of widgets for the Linac Coherent Light Source (LCLS) at SLAC

extra:
  recipe-maintainers:
    - klauer
    - zrylettc
    - zllentz
