{% set name = "pcdswidgets" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/pcdswidgets/archive/v{{ version }}.tar.gz
  sha256: 79c258ef7816fd57146f280ec7fa8c4c5e4ea80f38df2a87afce1563f0b8df4f

build:
  number: 2
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pydm >=1.9.0
    - qtpy

test:
  imports:
    - pcdswidgets

about:
  home: https://github.com/pcdshub/pcdswidgets
  doc_url: https://pcdshub.github.io/pcdswidgets/
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: PyDM library of widgets for the Linac Coherent Light Source (LCLS) at SLAC

extra:
  recipe-maintainers:
    - klauer
    - zrylettc
    - zllentz
